### ISSUE TITLE
Flutter-like syntax?

### ISSUE THREAD

**Issue by vtjiles** [Workiva/over_react#165]
> * Issue Type: [FEATURE REQUEST]

Still learning dart and over_react, but is it possible to create wrapper classes that follow the Flutter API syntax where children is set and no call method is required? 

I noticed discussion on issue https://github.com/Workiva/over_react/issues/41, but can't figure out how it would be implemented. It's just personal preference for structuring the code and saving a few parentheses. Thanks.

@montyclt's example:
```
new Div(
  prop: 'Value', //named parameter
  children: [
    'child1',
    'child2'
  ]
);
```

as opposed to:
```
(Dom.div()
  ..prop = 'Value'
)(
  'child1',
  'child2'
)
```

---

> __FYI:__ @greglittlefield-wf @aaronlademann-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf

**Comment by montyclt** [comment]
My proposition is a mix of flutter and over_react syntax like this:

```
// Calling component factory function.
Component(
  prop: 'Value' // Named parameters of props in first parenthesis.
)(
  'child1',
  'child2' // Children in the second parenthesis.
);
```

**Comment by aaronlademann-wf** [comment]
@vtjiles @montyclt at this time, the extra parentheses are necessary because the props are not arguments to a constructor - they are cascading setters on the builder.  The second set of parentheses invokes the builder.

We understand that it is a little out of the "norm", but believe me we have tried every alternative - and the parentheses are a necessary evil.

**Comment by FullstackJack** [comment]
Consider reopening. This would make moving to Dart an easier pill to swallow for most people coming to Dart/Flutter from React/React Native. If we can make the interfaces the same. We can ensure more people making the switch.
